# Generated by Django 4.1 on 2022-08-22 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_musica', models.CharField(max_length=200)),
                ('artista', models.CharField(max_length=200)),
                ('release_year', models.IntegerField()),
                ('lyrics', models.TextField()),
                ('data_musica', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
