# Generated by Django 4.1 on 2022-08-24 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('louvor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='cover_pic',
            field=models.ImageField(blank=True, upload_to='cover_pic'),
        ),
    ]
