# Generated by Django 4.1 on 2022-08-25 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0001_initial'),
        ('louvor', '0002_musica_cover_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musica',
            name='cover_pic',
        ),
        migrations.AlterField(
            model_name='musica',
            name='artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artista.artista'),
        ),
    ]
