# Generated by Django 4.1 on 2022-08-25 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('louvor', '0003_remove_musica_cover_pic_alter_musica_artista'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musica',
            old_name='artista',
            new_name='nome_artista',
        ),
    ]
