# Generated by Django 4.1 on 2022-08-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('louvor', '0004_rename_artista_musica_nome_artista'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='artista',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musica',
            name='cover_pic',
            field=models.ImageField(blank=True, upload_to='cover_pic'),
        ),
    ]
