# Generated by Django 4.1 on 2022-08-26 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('louvor', '0006_remove_musica_artista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musica',
            name='cover_pic',
        ),
    ]
