# Generated by Django 4.1 on 2022-09-24 01:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('louvor', '0010_musica_chords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_data', models.DateField(blank=True, default=datetime.datetime.now)),
                ('playlist_musicas', models.ManyToManyField(blank=True, to='louvor.musica')),
            ],
        ),
    ]
