# Generated by Django 4.1 on 2022-09-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='artista_pic',
            field=models.ImageField(blank=True, default='cover_img/default_artist.png', upload_to='cover_pic'),
        ),
    ]
