# Generated by Django 4.1 on 2022-09-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0002_alter_artista_artista_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='artista_pic',
            field=models.ImageField(blank=True, default='cover_pic/default_artist.png', upload_to='cover_pic'),
        ),
    ]
